services:
  node:
    command: bash
    image: node:18
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: node
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app